### PR TITLE
lk/npa breaking

### PR DESCRIPTION
**Pull request by lukekarrys**
- fix: handle new npm-package-arg semantics
- chore: bump hosted-git-info from 5.1.0 to 6.0.0
- chore: use ghi.addHost for git tests
- deps: npm-package-arg@10.0.0
- chore: @npmcli/template-oss@4.6.2

Closes #215
Closes #217 
Closes #230

### CODE REVIEW

**Comment by lukekarrys** [comment]
Seeing if CI passes on this. It includes hosted-git-info (#215) and npm-package-arg (#217) fixes which need to go together.

**Comment by wraithgar** [comment]
Thank you so much for picking this up where I left off

**Review by fritzy — APPROVED** [review]

**Comment by fritzy** [comment]
I saw you and gar removing the asterisk on specs… I’ll have to take your word for it, because I don’t have the context. LGTM

**Comment by wraithgar** [comment]
@fritzy the TLDR is that `npm`, `npm@` and `npm@*` are all now identical in how `npm-package-arg` parses things.

The way it used to work was that a bare package name (i.e. `npm`) would parse as identical to `npm@latest`.  This was not really correct, as it is npm in accordance with the `distTag` config that ends up finding the `latest` tag as the default if you specify a range that includes that tag.  So functionally an `npm install [pkg]` is not any different, it just lets `npm-pick-manifest` do its job instead of assuming `latest`.

This is one of those "technically correct" fixes that seems arbitrary but allowed us to remove quite a but of assumptive code that was working around this quirk.

**Pull request merged**
