### PR TITLE
fix(packument): eliminate _cached field

### PR DESCRIPTION
**Pull request by jablko**
I'm interested in telling whether the result of `pacote.manifest()` came from the registry or from the cacache. Is that what the existing packument `_cached` field indicates? https://github.com/npm/pacote/blob/298df450c03af17c069b8e40834d0154e801b61e/lib/registry.js#L77

If so, does it make sense to add that field to `pacote.manifest()` results, and is this PR the correct way/location to do it?

### CODE REVIEW

**Comment by wraithgar** [comment]
This seems reasonable. Can we add an assertion to one of the registry.js tests that ensures this got set?

**Comment by wraithgar** [comment]
`_cached` doesn't mean that the request was fed by the cache, but that it was stored in the cache.  I agree this doesn't appear to be very useful information, and there doesn't seem to be anywhere in the npm cli itself that we are evaluating this attribute.  Unfortunately removing it is a semver major change.  Perhaps the readme could be updated to clarify the distinction and we put a pin in either fixing it or removing it.

**Comment by lukekarrys** [comment]
@wraithgar This would be a good time to evaluate this change as we are on the verge of a major release of `pacote`?

**Comment by wraithgar** [comment]
@lukekarrys I checked again and we do not use this attribute.

**Pull request merged**
